name: Trigger Jenkins Job

on:
  workflow_dispatch:

jobs:
  trigger:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -i -X POST \
            -u "${{ secrets.USER }}:${{ secrets.TOKEN }}" \
            "${{ secrets.URL }}/job/youtube-sentiment-insight/build"